version: '3'

services:
  web: 
    image: nginx
    ports:
      - 80:80
    platform: linux/amd64
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432
  app:
    build: .
    volumes:
      - ./rails_app:/rails_app
    environment:
      - RAILS_ENV=${RAILS_ENV}
    env_file:
      - .env  
    ports:
      - 3000:3000
    depends_on:
      - db